[project]
name = "magical-athlete-frontend"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = ["marimo[lsp]", "magsim", "polars==1.24.0", "altair>=6.0.0"]

[tool.marimo.runtime]
output_max_bytes = 100_000_000
