[project]
name = "magical-athlete-frontend"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "marimo[lsp]",
    "magical-athlete-simulator",
    "polars>=1.36.1",
    "altair>=6.0.0",
]

[tool.uv.sources]
magical-athlete-simulator = { workspace = true }
