include_racers = [
    "Alchemist",
    "BabaYaga",
    "Banana",
    "Blimp",
    "Centaur",
    "Coach",
    "Copycat",
    "FlipFlop",
    "Genius",
    "Gunk",
    "Hare",
    "HugeBaby",
    "Inchworm",
    "Lackey",
    "Leaptoad",
    "Legs",
    "LovableLoser",
    "Magician",
    "Mastermind",
    "PartyAnimal",
    "Romantic",
    "Scoocher",
    "Sisyphus",
    "Skipper",
    "Stickler",
    "Suckerfish",
]
exclude_racers = []

# Test configurations
racer_counts = [4, 5, 6]
boards = ["standard", "wild_wilds"]

# Execution limits
runs_per_combination = 1
max_total_runs = 5_000
max_turns_per_race = 300

# --- Filters ---
[[filters]]
racers = ["Copycat", "Scoocher"]
boards = ["standard"]
